language: ruby
rvm:
    - 2.6
script: 'bundle exec jekyll build'
cache: bundler
os: osx
deploy:
    provider: pages
    token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
    keep_history: true
    local_dir: _site
    target_branch: master
    on:
        branch: develop
